# Generated by Django 5.2.2 on 2025-06-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresult',
            name='hp_remaining',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
