# Generated by Django 5.2.2 on 2025-06-09 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gameresult_hp_remaining'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='winner',
        ),
    ]
